su - db2inst1 << EOF
db2 connect to $DBNAME
db2 CREATE BUFFERPOOL MAXBUFPOOL IMMEDIATE SIZE 4096 AUTOMATIC PAGESIZE 32 K

db2 CREATE REGULAR TABLESPACE MAXDATA PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE INITIALSIZE 5000 M BUFFERPOOL MAXBUFPOOL
db2 CREATE TEMPORARY TABLESPACE MAXTEMP PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL MAXBUFPOOL
db2 CREATE REGULAR TABLESPACE MAXINDEX PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE INITIALSIZE 5000 M BUFFERPOOL MAXBUFPOOL

db2 create schema $SCHEMA_USERNAME authorization $SCHEMA_PASSWORD

db2 GRANT USE OF TABLESPACE MAXDATA TO USER $SCHEMA_USERNAME
db2 GRANT USE OF TABLESPACE MAXINDEX TO USER $SCHEMA_USERNAME


db2 GRANT DBADM,CREATETAB,BINDADD,CONNECT,CREATE_NOT_FENCED_ROUTINE,IMPLICIT_SCHEMA, LOAD,CREATE_EXTERNAL_ROUTINE,QUIESCE_CONNECT,SECADM ON DATABASE TO USER MAXIMO
db2 GRANT CREATEIN,DROPIN,ALTERIN ON SCHEMA $SCHEMA_USERNAME TO USER $SCHEMA_USERNAME

EOF

# create user maximo for database access. we could have used db2inst1 but it is maximo 76 standard credentials this way
useradd $SCHEMA_USERNAME -G db2iadm1,wheel
echo "$SCHEMA_PASSWORD" | passwd $SCHEMA_USERNAME --stdin

# This line is used to not run the scripts everytime the container restarts.
rm -f /var/custom/*.sh